### ISSUE TITLE
On screen keyboard

### ISSUE THREAD

**Issue by Gamerein** [nicu03/dark-youtube-theme#46]
So youtube has an onscreen-keyboard. And it's unchanged. Maybe add something like:
```CSS
/* on-screen keyboard*/
div#kbd {
    background-color: var(--menu-bg-color);
}

.vk-t {
    background-color: #FFF;
    width: 485px;
    padding-left: 10px;
    border-radius: 10px;
    margin-bottom: 2px;
}
```
too make it black as well
